import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import 'dotenv/config';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const requiredVars = [
    'VITE_FIREBASE_API_KEY',
    'VITE_FIREBASE_AUTH_DOMAIN',
    'VITE_FIREBASE_PROJECT_ID',
    'VITE_FIREBASE_STORAGE_BUCKET',
    'VITE_FIREBASE_MESSAGING_SENDER_ID',
    'VITE_FIREBASE_APP_ID',
    'VITE_FIREBASE_DATABASE_URL',
];

const missing = requiredVars.filter((key) => !process.env[key]);
if (missing.length > 0) {
    console.error(`Missing env vars for service worker generation: ${missing.join(', ')}`);
    process.exit(1);
}

const template = `// This file is auto-generated by scripts/generate-sw.js — do not edit directly.
// Run "npm run build" (or "node scripts/generate-sw.js") to regenerate it from your .env file.

importScripts('https://www.gstatic.com/firebasejs/12.9.0/firebase-app-compat.js');
importScripts('https://www.gstatic.com/firebasejs/12.9.0/firebase-messaging-compat.js');

const firebaseConfig = {
    apiKey: '${process.env.VITE_FIREBASE_API_KEY}',
    authDomain: '${process.env.VITE_FIREBASE_AUTH_DOMAIN}',
    projectId: '${process.env.VITE_FIREBASE_PROJECT_ID}',
    storageBucket: '${process.env.VITE_FIREBASE_STORAGE_BUCKET}',
    messagingSenderId: '${process.env.VITE_FIREBASE_MESSAGING_SENDER_ID}',
    appId: '${process.env.VITE_FIREBASE_APP_ID}',
    databaseURL: '${process.env.VITE_FIREBASE_DATABASE_URL}',
};

firebase.initializeApp(firebaseConfig);

const messaging = firebase.messaging();

messaging.onBackgroundMessage((payload) => {
    const title = payload?.notification?.title || 'Smart Bachelor Life';
    const options = {
        body: payload?.notification?.body || 'You have a new notification.',
        icon: '/favicon.ico',
        tag: 'smart-bachelor-life-notification',
    };

    return self.registration.showNotification(title, options);
});

self.addEventListener('notificationclick', (event) => {
    event.notification.close();
    event.waitUntil(
        clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
            for (const client of clientList) {
                if (client.url.includes(self.location.origin) && 'focus' in client) {
                    return client.focus();
                }
            }
            if (clients.openWindow) {
                return clients.openWindow('/');
            }
        })
    );
});
`;

const outputPath = path.join(__dirname, '..', 'public', 'firebase-messaging-sw.js');
fs.writeFileSync(outputPath, template.trim() + '\n');
console.log(`firebase-messaging-sw.js generated at ${outputPath}`);
